travis:
  secure:
    BINSTAR_TOKEN: eD4Xf4lSGbrPQ/yyWO3zITJ7ZaEv4Anjx4gxlAcl5luivKtkO9suUn2xLPUVVbbTB6WDwcvrHtUrXx1NrVO/eC4XQu5Ov4MWpZo+ypHggiPQlP57+LhigU8oB5qgCBT2/Xp2shnm5A5PzzVuoaBOaB6VKkOLb0CcV0+bWFi0LBopCgG4I8k2kj/UDS2EH+WsSOG5P8/O9A3PVkNnkjZRGl8f2cUHlAxkn4F/PvY/BCvcmIlcXcqSvK7M8nVegQ/6uputd7Nin1za5kMM6ZKcIdy7UaRGPi6ky218x+oOO8FL3gY9MV4pOtX3XdY2yH78aO7furvvYBddiN4r1/sTEaZ2dxdedu3xqkYQQn9xH0J+h1YGeNNeASKXVpU6h9m37bbirXo+bqmVhr/UHhKfLQ6moPxIGYINVrODFIB0agH3//Dg+yXV62C37qWhJvUEr8u/86aqvN7CIfjiqSFIBSHoECVOcfOx77cU3hx0MBJ0W08NYtj+cqeMekeOPQkwC6u8fm5ctZgTaRiuRgIYXaD3Od3KAhspjTPpEXEc3BlFbEOEsR33enPOsYXtEYsXGxGCtf0EvWkPoODFJ0m5DD8zddnyMHmMkG/ZdhmhZhhg+S9o5qtGR6SWj+lYgmqtGrs1RUk99uCdVOSYesJgbyi/r6g3WYsgfL4LuVpCxho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
